name: Backend CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend-laravel/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend-laravel/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: fashion_cloth_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    strategy:
      matrix:
        php-version: [8.1, 8.2]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, bcmath, soap, zip
        coverage: none
    
    - name: Install backend dependencies
      run: |
        cd backend-laravel
        composer install --no-interaction --prefer-dist --optimize-autoloader
    
    - name: Copy environment file
      run: |
        cd backend-laravel
        cp .env.example .env
    
    - name: Generate application key
      run: |
        cd backend-laravel
        php artisan key:generate
    
    - name: Run PHP linter
      run: |
        cd backend-laravel
        find ./app -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
    
    - name: Run tests
      run: |
        cd backend-laravel
        php artisan test
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: fashion_cloth_test
        DB_USERNAME: root
        DB_PASSWORD: password

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to production server
      run: |
        echo "Deploying to production server..."
        # Add your deployment commands here
        # For example, using SSH to deploy to a server:
        # ssh user@your-server.com "cd /var/www/html && git pull origin main && composer install --no-dev && php artisan migrate --force"