name: Frontend CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend_react/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend_react/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend_react/package-lock.json
    
    - name: Install frontend dependencies
      run: |
        cd frontend_react
        npm ci
    
    - name: Run linting
      run: |
        cd frontend_react
        npm run lint
    
    - name: Run tests
      run: |
        cd frontend_react
        npm test -- --watchAll=false
      continue-on-error: true
    
    - name: Build frontend
      run: |
        cd frontend_react
        npm run build
    
    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: frontend-build
        path: frontend_react/dist

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: frontend-build
        path: frontend_react/dist
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend_react/dist
        cname: your-domain.com  # Replace with your custom domain if needed